### ISSUE TITLE
这个方案是没用了

### ISSUE THREAD

**Issue by roths** [lightai/LayoutConverter#1]
研究了一天，发现这个demo代码之所以显示编译生成代码的方式更快，是因为代码调用顺序是先用inflate方式创建View Tree，然后用编译生成的Java Code创建View Tree。
表面上是快了，实际上跟方式无关，是因为后者用了TypeArray的缓存所以更快了，调用顺序在后面的都会命中TypeArray缓存从而显得更快。

**Comment by lightai** [comment]
创建view树最大的开销是：创建节点view的开销。这种方式支持异步线程创建一批view对象，创建view树的时候直接使用创建好的view对象，性能可以得到很大提升。
参考：https://github.com/lightai/LayoutConverter/blob/master/androidlibrary/src/main/java/com/netease/layoutconverter/ViewFactory.java

**Comment by lightai** [comment]
另外这种异步创建view的思路，已经用到手淘里，且经过双11验证，ui性能提升显著。

**Comment by roths** [comment]
这个方案用在异步确实可以
